Algoritmo "job1"

Var
// Seção de Declarações das variáveis 
//TIPOS DE DADOS
//caractere - texto
nome : caractere
//real - decimal, numeros quebrados
valor : real
//inteiro - "valor redondo'
idade: inteiro
//logico - verdadeiro e falso, boolear
ligado : logico

// regras de variaveis
//1 - não pode palavras dedicadas
//2 - não pode caractere especial
//3 - não pode caentos e cedilha
//4 - não pode começar com numero / só o numero
//5 - não pode espaços vazios
//     * camel case - nomeComposto
//     * snake case - nome_composto
//     * upper case - NOMECOMPOSTO (maiusculo)
//     * lower case - nomecomposto ( mminusculo)
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("olá mundo")
escreval("estou aprendendo a programar")
escreval(3 + 1230287482)

Fimalgoritmo